"use client";
import {useEffect,useMemo,useState} from "react";
import {ChevronLeft,ChevronRight,Plus,Share2,X,Pencil,Trash2,CalendarDays,LockKeyhole} from "lucide-react";
import type {CalendarEvent} from "@/lib/types";
const colors:Record<string,string>={lavender:"#E9E2FF",sage:"#DDEFE4",peach:"#FFE6D7",blue:"#DCEBFF",rose:"#FFE0EA"};
async function safeJson(r:Response){const t=await r.text();try{return t?JSON.parse(t):{}}catch{return{error:`Server error (${r.status})`}}}
export default function CalendarApp({calendarId}:{calendarId:string}){
 const now=new Date(); const [cursor,setCursor]=useState(new Date(now.getFullYear(),now.getMonth(),1)); const [events,setEvents]=useState<CalendarEvent[]>([]); const [loading,setLoading]=useState(true); const [modal,setModal]=useState<"create"|"edit"|null>(null); const [selected,setSelected]=useState<CalendarEvent|null>(null); const [passwordOpen,setPasswordOpen]=useState(false); const [pending,setPending]=useState<"edit"|"delete"|null>(null); const [password,setPassword]=useState(""); const [error,setError]=useState(""); const [form,setForm]=useState({title:"",date:"",startTime:"",endTime:"",location:"",description:"",color:"lavender"});
 const y=cursor.getFullYear(),m=cursor.getMonth(),days=new Date(y,m+1,0).getDate(),offset=new Date(y,m,1).getDay(),month=cursor.toLocaleString("en-US",{month:"long",year:"numeric"}); const cells=useMemo(()=>Array.from({length:Math.ceil((offset+days)/7)*7},(_,i)=>i-offset+1),[offset,days]);
 const load=async()=>{setLoading(true);try{const r=await fetch(`/api/events?calendarId=${encodeURIComponent(calendarId)}`,{cache:"no-store"});const d=await safeJson(r);if(!r.ok)throw Error(d.error||"Unable to load events.");setEvents(Array.isArray(d)?d:[])}catch(e){setError(e instanceof Error?e.message:"Unable to load events.")}finally{setLoading(false)}}; useEffect(()=>{load()},[calendarId]);
 const openCreate=(date?:string)=>{setError("");setSelected(null);setForm({title:"",date:date||`${y}-${String(m+1).padStart(2,"0")}-${String(now.getDate()).padStart(2,"0")}`,startTime:"",endTime:"",location:"",description:"",color:"lavender"});setModal("create")};
 const request=(e:CalendarEvent,a:"edit"|"delete")=>{setSelected(e);setPending(a);setPassword("");setError("");setPasswordOpen(true)};
 const secure=async()=>{if(!selected||!pending)return;if(!password){setError("Enter the password.");return}if(pending==="edit"){setForm({title:selected.title,date:selected.date,startTime:selected.startTime||"",endTime:selected.endTime||"",location:selected.location||"",description:selected.description||"",color:selected.color||"lavender"});setPasswordOpen(false);setModal("edit");return}try{const r=await fetch(`/api/events/${selected.id}`,{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({password})});const d=await safeJson(r);if(!r.ok)throw Error(d.error||"Delete failed.");setPasswordOpen(false);setSelected(null);load()}catch(e){setError(e instanceof Error?e.message:"Delete failed.")}};
 const save=async()=>{setError("");if(!form.title.trim()||!form.date){setError("Please add a title and date.");return}try{const edit=modal==="edit"&&selected;const r=await fetch(edit?`/api/events/${selected!.id}`:"/api/events",{method:edit?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(edit?{...form,password}:{...form,calendarId})});const d=await safeJson(r);if(!r.ok)throw Error(d.error||"Save failed.");setModal(null);setSelected(null);setPassword("");load()}catch(e){setError(e instanceof Error?e.message:"Save failed.")}};
 const share=async()=>{const url=`${location.origin}/calendar/${calendarId}`;try{await navigator.clipboard.writeText(url);setError("Share link copied.")}catch{setError(url)}};
 const eventFor=(d:number)=>{const k=`${y}-${String(m+1).padStart(2,"0")}-${String(d).padStart(2,"0")}`;return events.filter(e=>e.date===k)};
 return <main className="shell"><header className="topbar"><div className="brand"><div className="brandMark"><CalendarDays size={21}/></div><div><div className="brandName">IMPROX</div><div className="brandSub">GROUP CALENDAR</div></div></div><div className="actions"><button className="ghost" onClick={share}><Share2 size={17}/> Share</button><button className="primary" onClick={()=>openCreate()}><Plus size={18}/> Add event</button></div></header>
 <section className="calendarCard"><div className="calendarHead"><div><div className="eyebrow">SCHEDULE</div><h1>{month}</h1></div><div className="nav"><button onClick={()=>setCursor(new Date(y,m-1,1))}><ChevronLeft/></button><button onClick={()=>setCursor(new Date(y,m+1,1))}><ChevronRight/></button></div></div>{error&&<div className="notice">{error}</div>}<div className="weekdays">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(d=><div key={d}>{d}</div>)}</div><div className="grid">{cells.map((d,i)=>{const valid=d>0&&d<=days;const key=valid?`${y}-${String(m+1).padStart(2,"0")}-${String(d).padStart(2,"0")}`:"";const isToday=key===`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}-${String(now.getDate()).padStart(2,"0")}`;return <div className={`day ${!valid?"empty":""}`} key={i} onDoubleClick={()=>valid&&openCreate(key)}>{valid&&<><div className={`dayNum ${isToday?"today":""}`}>{d}</div><div className="events">{eventFor(d).map(e=><button key={e.id} className="event" style={{background:colors[e.color||"lavender"]}} onClick={ev=>{ev.stopPropagation();request(e,"edit")}}><span>{e.startTime&&`${e.startTime} · `}{e.title}</span></button>)}</div></>}</div>})}</div>{loading&&<div className="loading">Loading calendar…</div>}<div className="hint"><span>Tip</span> Double-click any day to add an event. Click an event to edit or delete it.</div></section>
 {modal&&<div className="overlay"><div className="modal"><div className="modalHead"><div><div className="eyebrow">{modal==="edit"?"EDIT EVENT":"NEW EVENT"}</div><h2>{modal==="edit"?"Refine your schedule":"Add to your calendar"}</h2></div><button className="close" onClick={()=>setModal(null)}><X/></button></div><div className="form"><label>Event title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="e.g. Leadership meeting"/></label><div className="two"><label>Date<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>Location<input value={form.location} onChange={e=>setForm({...form,location:e.target.value})} placeholder="Optional"/></label></div><div className="two"><label>Start<input type="time" value={form.startTime} onChange={e=>setForm({...form,startTime:e.target.value})}/></label><label>End<input type="time" value={form.endTime} onChange={e=>setForm({...form,endTime:e.target.value})}/></label></div><label>Description<textarea rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Add notes…"/></label><label>Accent<div className="swatches">{Object.keys(colors).map(c=><button type="button" key={c} className={`swatch ${form.color===c?"selected":""}`} style={{background:colors[c]}} onClick={()=>setForm({...form,color:c})}/>)}</div></label>{modal==="edit"&&<div className="passwordNote"><LockKeyhole size={16}/> Changes require the edit password.</div>}<button className="primary full" onClick={save}>{modal==="edit"?"Save changes":"Create event"}</button></div></div></div>}
 {passwordOpen&&selected&&<div className="overlay"><div className="modal small"><div className="modalHead"><div><div className="eyebrow">SECURE ACTION</div><h2>{pending==="delete"?"Delete event?":"Edit event"}</h2></div><button className="close" onClick={()=>setPasswordOpen(false)}><X/></button></div><p className="muted">{pending==="delete"?"This will permanently remove the event.":"Enter the edit password to continue."}</p><label>Password<input type="password" autoFocus value={password} onChange={e=>setPassword(e.target.value)} onKeyDown={e=>e.key==="Enter"&&secure()} placeholder="Enter password"/></label>{error&&<div className="error">{error}</div>}<div className="secureActions"><button className="ghost" onClick={()=>setPasswordOpen(false)}>Cancel</button>{pending==="delete"?<button className="danger" onClick={secure}><Trash2 size={16}/> Delete</button>:<button className="primary" onClick={secure}><Pencil size={16}/> Continue</button>}</div></div></div>}</main>
}